# Generated by Django 5.1.3 on 2024-12-05 07:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dependent',
            name='profile',
        ),
        migrations.AlterModelOptions(
            name='dependent',
            options={'verbose_name': 'Dependent', 'verbose_name_plural': 'Dependents'},
        ),
        migrations.RemoveField(
            model_name='dependent',
            name='not_applicable',
        ),
        migrations.AlterField(
            model_name='dependent',
            name='age',
            field=models.PositiveIntegerField(default=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dependent',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dependent',
            name='relationship',
            field=models.CharField(choices=[('Father', 'Father'), ('Mother', 'Mother'), ('Spouse', 'Spouse'), ('Child', 'Child')], max_length=20),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit_posted', models.CharField(max_length=255)),
                ('sap_id', models.CharField(max_length=50, unique=True)),
                ('ppo_number', models.CharField(blank=True, max_length=50, null=True)),
                ('mobile_number', models.CharField(max_length=15)),
                ('email_id', models.EmailField(max_length=254)),
                ('designation', models.CharField(max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='dependent',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='user_management_app.employee'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
