# Generated by Django 5.1.3 on 2024-12-16 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management_app', '0002_remove_dependent_profile_alter_dependent_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mobile_number',
            field=models.CharField(max_length=10),
        ),
    ]
