# Generated by Django 5.1.3 on 2024-12-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management_app', '0003_alter_employee_mobile_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], default=None, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='pay_matrix',
            field=models.CharField(default=None, max_length=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='serving_status',
            field=models.CharField(choices=[('Serving', 'Serving'), ('Retired', 'Retired')], default=None, max_length=8),
            preserve_default=False,
        ),
    ]
