# Generated by Django 5.1.3 on 2024-12-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management_app', '0004_employee_gender_employee_pay_matrix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1),
        ),
        migrations.AlterField(
            model_name='employee',
            name='pay_matrix',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='employee',
            name='serving_status',
            field=models.CharField(blank=True, choices=[('Serving', 'Serving'), ('Retired', 'Retired')], max_length=8),
        ),
    ]
