# Generated by Django 5.1.3 on 2024-12-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_management_app', '0005_alter_employee_gender_alter_employee_pay_matrix_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Others')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='serving_status',
            field=models.CharField(choices=[('Serving', 'Serving'), ('Retired', 'Retired')], max_length=8, null=True),
        ),
    ]
