# Generated by Django 5.1.3 on 2025-01-02 05:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_reimbursement_app', '0001_initial'),
        ('user_management_app', '0007_alter_employee_gender_alter_employee_serving_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalreimbursement',
            name='hospital_name',
        ),
        migrations.RemoveField(
            model_name='medicalreimbursement',
            name='hospital_type',
        ),
        migrations.RemoveField(
            model_name='medicalreimbursement',
            name='income_tax_exempt',
        ),
        migrations.AlterField(
            model_name='medicalreimbursement',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user_management_app.dependent'),
        ),
    ]
